default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-sock-monster_development

test:
  <<: *default
  database: rails-sock-monster_test
